import { Jersey_25 } from 'next/font/google';

const jersey = Jersey_25({
  subsets: ['latin'],
  weight: '400',
});

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${jersey.className} antialiased`}
      >
        {children}
      </body>
    </html>
    
  );
}
